# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: deploy-surge

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Installing surge
      run: npm install --global surge
           surge token fb18b1b0084ca4dd8551b42d638bd08b
           surge --project ./ --domain https://envious-brother.surge.sh/ 
